//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiLogs
    {
        public int LogId { get; set; }
        public System.DateTime LogDate { get; set; }
        public string Exception { get; set; }
        public string StackTrace { get; set; }
    }
}
